# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Leonardo Martins
title_html: "leonardo<b>martins</b>.com"
email: contato@leonardomartins.com
description: > # this means to ignore newlines until "baseurl:"
  Energy specialist interested in the operation and economics of power systems with emphasis on the Brazilian electricity markets.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author: Leonardo Martins
author_website: https://scholar.google.com/citations?user=esE9giIAAAAJ
curriculum:
  name: Résumé
  url: assets/cv.pdf
linkedin_username: snitramodranoel
github_username:  snitramodranoel
twitter_username: snitramodranoel
cc: by-nc-nd

# Build settings
markdown: kramdown
#redcarpet:
#  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data", "no_intra_emphasis"]

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
